github.com:
    git_protocol: ssh
    users:
        RefinedChicken:
            oauth_token: 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
    user: RefinedChicken
    oauth_token: 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
